senyawa_data = {
    "Asam Sulfat": {
        "rumus": "H2SO4",
        "simbol_bahaya": "Korosif",
        "wujud": "Cairan kental",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat reaktif terhadap air (eksotermis hebat) dan logam (menghasilkan gas H2); bersifat dehidrator kuat; mengkarbonasi senyawa organik; netralisasi eksotermis dengan basa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan asam (kaca atau plastik HDPE), beri label jelas 'LIMBAH B3 - ASAM KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan NaOH 10% atau Na2CO3 padat sambil diaduk perlahan hingga pH netral (6-8).\nLangkah 3: Uji pH dengan kertas indikator universal \u2014 pastikan pH aman.\nLangkah 4: Encerkan dengan air mengalir (perbandingan 1:10).\nLangkah 5: Buang ke saluran pembuangan khusus B3 atau serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Asam Klorida": {
        "rumus": "HCl",
        "simbol_bahaya": "Korosif",
        "wujud": "Cairan",
        "bau": "Menyengat",
        "reaktivitas": "Reaktif terhadap logam aktif (Zn, Fe, Mg) menghasilkan gas H2; bereaksi hebat dengan basa kuat membentuk garam; mengkorosi banyak logam; netralisasi eksotermis",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan asam (kaca atau plastik HDPE), beri label jelas 'LIMBAH B3 - ASAM KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan NaOH 10% atau Na2CO3 padat sambil diaduk perlahan hingga pH netral (6-8).\nLangkah 3: Uji pH dengan kertas indikator universal \u2014 pastikan pH aman.\nLangkah 4: Encerkan dengan air mengalir (perbandingan 1:10).\nLangkah 5: Buang ke saluran pembuangan khusus B3 atau serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Asam Nitrat": {
        "rumus": "HNO3",
        "simbol_bahaya": "Oksidator korosif",
        "wujud": "Cairan",
        "bau": "Menyengat",
        "reaktivitas": "Oksidator kuat; bereaksi hebat dengan logam (menghasilkan NOx), bahan organik (oksidasi), dan basa (netralisasi); dapat meledak dengan bahan pereduksi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan asam, beri label 'LIMBAH B3 - ASAM OKSIDATOR'. Jangan campur dengan bahan organik.\nLangkah 2: Netralisasi dengan larutan NaOH 10% perlahan (oksidator kuat, jangan sampai bereaksi hebat).\nLangkah 3: Uji pH hingga netral (6-8).\nLangkah 4: Encerkan 1:10 dengan air.\nLangkah 5: Serahkan ke pengelola limbah B3 bersertifikat \u2014 jangan dibuang langsung ke saluran umum tanpa izin.",
    },
    "Asam Fosfat": {
        "rumus": "H3PO4",
        "simbol_bahaya": "Korosif",
        "wujud": "Cairan kental",
        "bau": "Tidak berbau",
        "reaktivitas": "Reaktif terhadap basa melalui netralisasi bertahap (3 tahap); korosif terhadap logam tertentu; bereaksi lambat dengan air (eksotermis ringan)",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan asam (kaca atau plastik HDPE), beri label jelas 'LIMBAH B3 - ASAM KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan NaOH 10% atau Na2CO3 padat sambil diaduk perlahan hingga pH netral (6-8).\nLangkah 3: Uji pH dengan kertas indikator universal \u2014 pastikan pH aman.\nLangkah 4: Encerkan dengan air mengalir (perbandingan 1:10).\nLangkah 5: Buang ke saluran pembuangan khusus B3 atau serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Asam Asetat": {
        "rumus": "CH3COOH",
        "simbol_bahaya": "Korosif mudah terbakar",
        "wujud": "Cairan",
        "bau": "Asam cuka",
        "reaktivitas": "Bereaksi dengan basa membentuk garam asetat; korosif terhadap logam aktif; dapat mengalami esterifikasi dengan alkohol; mudah terbakar jika terkena api",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Natrium Hidroksida": {
        "rumus": "NaOH",
        "simbol_bahaya": "Korosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat reaktif terhadap asam (netralisasi hebat); bereaksi dengan logam Al dan Zn menghasilkan gas H2; menyerap CO2 dari udara membentuk karbonat; higroskopis kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan basa (plastik HDPE), beri label 'LIMBAH B3 - BASA KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan HCl 10% atau H2SO4 encer sambil diaduk hingga pH 6-8.\nLangkah 3: Uji pH dengan kertas indikator universal.\nLangkah 4: Encerkan dengan air mengalir (1:10).\nLangkah 5: Buang ke saluran pembuangan atau serahkan ke pengelola limbah B3.",
    },
    "Kalium Hidroksida": {
        "rumus": "KOH",
        "simbol_bahaya": "Korosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat reaktif terhadap asam (netralisasi hebat); bereaksi dengan logam Al dan Zn menghasilkan gas H2; menyerap CO2 dan uap air dari udara; higroskopis kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan basa (plastik HDPE), beri label 'LIMBAH B3 - BASA KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan HCl 10% atau H2SO4 encer sambil diaduk hingga pH 6-8.\nLangkah 3: Uji pH dengan kertas indikator universal.\nLangkah 4: Encerkan dengan air mengalir (1:10).\nLangkah 5: Buang ke saluran pembuangan atau serahkan ke pengelola limbah B3.",
    },
    "Amonia": {
        "rumus": "NH3",
        "simbol_bahaya": "Beracun korosif",
        "wujud": "Gas/cair",
        "bau": "Menyengat",
        "reaktivitas": "Bereaksi dengan asam membentuk garam amonium; bersifat basa lemah dalam air (NH4OH); bereaksi dengan ion logam membentuk kompleks amina; iritasi kuat pada mukosa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tertutup rapat (uap amonia), beri label 'LIMBAH BASA'.\nLangkah 2: Encerkan dengan air (1:5) di area berventilasi.\nLangkah 3: Netralisasi dengan asam encer (HCl 10%) hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Kalsium Hidroksida": {
        "rumus": "Ca(OH)2",
        "simbol_bahaya": "Korosif",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Bereaksi dengan asam membentuk garam kalsium; menyerap CO2 dari udara membentuk CaCO3; bereaksi lambat dengan air membentuk suspensi basa; basa lemah",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tertutup rapat (uap amonia), beri label 'LIMBAH BASA'.\nLangkah 2: Encerkan dengan air (1:5) di area berventilasi.\nLangkah 3: Netralisasi dengan asam encer (HCl 10%) hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Etanol": {
        "rumus": "C2H5OH",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Cairan",
        "bau": "Khas alkohol",
        "reaktivitas": "Mudah terbakar membakar dengan nyala biru muda; bereaksi dengan oksidator kuat (KMnO4, K2Cr2O7) menjadi asetaldehida/asam asetat; stabil pada suhu kamar",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca atau logam tertutup rapat, beri label 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Jangan dicampur dengan oksidator atau asam kuat (risiko kebakaran).\nLangkah 3: Simpan di lemari asam berventilasi, jauh dari api, panas, dan percikan listrik.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi suhu tinggi.",
    },
    "Metanol": {
        "rumus": "CH3OH",
        "simbol_bahaya": "Mudah terbakar beracun",
        "wujud": "Cairan",
        "bau": "Khas alkohol",
        "reaktivitas": "Mudah terbakar; bereaksi dengan oksidator kuat; toksik (dapat menyebabkan kebutaan); teroksidasi menjadi formaldehida dan asam format oleh enzim alkohol dehidrogenase",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca atau logam tertutup rapat, beri label 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Jangan dicampur dengan oksidator atau asam kuat (risiko kebakaran).\nLangkah 3: Simpan di lemari asam berventilasi, jauh dari api, panas, dan percikan listrik.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi suhu tinggi.",
    },
    "Isopropanol": {
        "rumus": "C3H7OH",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Cairan",
        "bau": "Khas alkohol",
        "reaktivitas": "Mudah terbakar dengan nyala terang; bereaksi dengan oksidator kuat; teroksidasi menjadi aseton; stabil pada suhu kamar; mudah menguap",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca atau logam tertutup rapat, beri label 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Jangan dicampur dengan oksidator atau asam kuat (risiko kebakaran).\nLangkah 3: Simpan di lemari asam berventilasi, jauh dari api, panas, dan percikan listrik.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi suhu tinggi.",
    },
    "Aseton": {
        "rumus": "(CH3)2CO",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Mudah terbakar dan mudah menguap; bereaksi dengan oksidator kuat; melarutkan banyak senyawa organik dan polimer; stabil pada suhu kamar; reaksi halogenasi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca atau logam tertutup rapat, beri label 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Jangan dicampur dengan oksidator atau asam kuat (risiko kebakaran).\nLangkah 3: Simpan di lemari asam berventilasi, jauh dari api, panas, dan percikan listrik.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi suhu tinggi.",
    },
    "Etil Asetat": {
        "rumus": "CH3COOC2H5",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Cairan",
        "bau": "Buah",
        "reaktivitas": "Mudah terbakar; bereaksi dengan basa kuat mengalami hidrolisis menjadi asam asetat dan etanol; stabil dalam kondisi netral; pelarut organik umum",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca atau logam tertutup rapat, beri label 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Jangan dicampur dengan oksidator atau asam kuat (risiko kebakaran).\nLangkah 3: Simpan di lemari asam berventilasi, jauh dari api, panas, dan percikan listrik.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi suhu tinggi.",
    },
    "n-Heksana": {
        "rumus": "C6H14",
        "simbol_bahaya": "Mudah terbakar berbahaya",
        "wujud": "Cairan",
        "bau": "Bensin",
        "reaktivitas": "Sangat mudah terbakar; bereaksi dengan oksidator kuat; stabil pada suhu kamar; inert terhadap asam dan basa; pelarut non-polar; uap lebih berat dari udara",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Dietil Eter": {
        "rumus": "C2H5OC2H5",
        "simbol_bahaya": "Sangat mudah terbakar",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Sangat mudah terbakar dan mudah menguap; dapat membentuk peroksida eksplosif jika terkena udara dan cahaya; stabil dalam wadah tertutup rapat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Benzena": {
        "rumus": "C6H6",
        "simbol_bahaya": "Karsinogen mudah terbakar",
        "wujud": "Cairan",
        "bau": "Aromatis",
        "reaktivitas": "Mudah terbakar dengan nyala berjelaga; bereaksi substitusi elektrofilik (nitrasi, sulfonasi, halogenasi); karsinogenik; stabil pada suhu kamar",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Toluena": {
        "rumus": "C7H8",
        "simbol_bahaya": "Mudah terbakar beracun",
        "wujud": "Cairan",
        "bau": "Aromatis",
        "reaktivitas": "Mudah terbakar; bereaksi substitusi elektrofilik lebih cepat dari benzena; teroksidasi menjadi asam benzoat; stabil pada suhu kamar; toksik bagi sistem saraf",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Kloroform": {
        "rumus": "CHCl3",
        "simbol_bahaya": "Beracun",
        "wujud": "Cairan",
        "bau": "Manis",
        "reaktivitas": "Stabil pada suhu kamar; terurai pada suhu tinggi atau terkena cahaya UV menghasilkan fosgen (COCl2) dan HCl beracun; inert terhadap banyak reagen",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca gelap tertutup rapat, beri label 'LIMBAH B3 - TOKSIK HALOGEN'.\nLangkah 2: Hindari kontak dengan kulit dan inhalasi uap.\nLangkah 3: Jangan dicampur dengan limbah lain.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus (tidak bisa diinsinerasi biasa).",
    },
    "Diklorometana": {
        "rumus": "CH2Cl2",
        "simbol_bahaya": "Beracun",
        "wujud": "Cairan",
        "bau": "Manis",
        "reaktivitas": "Stabil pada suhu kamar; tidak mudah terbakar; terurai pada suhu tinggi menghasilkan HCl dan gas beracun; pelarut organik yang relatif inert",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca gelap tertutup rapat, beri label 'LIMBAH B3 - TOKSIK HALOGEN'.\nLangkah 2: Hindari kontak dengan kulit dan inhalasi uap.\nLangkah 3: Jangan dicampur dengan limbah lain.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus (tidak bisa diinsinerasi biasa).",
    },
    "Karbon Tetraklorida": {
        "rumus": "CCl4",
        "simbol_bahaya": "Beracun",
        "wujud": "Cairan",
        "bau": "Manis",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak mudah terbakar; terurai pada suhu tinggi menjadi fosgen dan HCl; toksik bagi hati; inert terhadap asam dan basa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca gelap tertutup rapat, beri label 'LIMBAH B3 - TOKSIK HALOGEN'.\nLangkah 2: Hindari kontak dengan kulit dan inhalasi uap.\nLangkah 3: Jangan dicampur dengan limbah lain.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus (tidak bisa diinsinerasi biasa).",
    },
    "Hidrogen Peroksida": {
        "rumus": "H2O2",
        "simbol_bahaya": "Oksidator korosif",
        "wujud": "Cairan",
        "bau": "Tajam",
        "reaktivitas": "Oksidator kuat; terurai terkena cahaya, panas, atau katalis (MnO2) menjadi air dan oksigen; bereaksi hebat dengan bahan organik dan logam; bleaching agent",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik atau kaca berlabel 'LIMBAH B3 - OKSIDATOR'. Jangan campur dengan bahan organik.\nLangkah 2: Encerkan dengan air (1:10) secara perlahan.\nLangkah 3: Reduksi jika perlu dengan natrium tiosulfat.\nLangkah 4: Netralisasi pH hingga 6-8.\nLangkah 5: Serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Kalium Permanganat": {
        "rumus": "KMnO4",
        "simbol_bahaya": "Oksidator",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Oksidator sangat kuat dalam suasana asam; bereaksi hebat dengan bahan organik, alkohol, dan pereduksi; larutan ungu berubah menjadi coklat (MnO2) saat bereaksi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik atau kaca berlabel 'LIMBAH B3 - OKSIDATOR'. Jangan campur dengan bahan organik.\nLangkah 2: Encerkan dengan air (1:10) secara perlahan.\nLangkah 3: Reduksi dengan natrium tiosulfat atau asam oksalat hingga tidak berwarna.\nLangkah 4: Netralisasi pH hingga 6-8.\nLangkah 5: Serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Kalium Dikromat": {
        "rumus": "K2Cr2O7",
        "simbol_bahaya": "Oksidator toksik",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Oksidator kuat dalam suasana asam; bereaksi dengan alkohol dan senyawa organik; toksik dan karsinogenik; larutan jingga berubah menjadi hijau (Cr3+) saat tereduksi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik atau kaca berlabel 'LIMBAH B3 - OKSIDATOR TOKSIK'. Jangan campur dengan bahan organik.\nLangkah 2: Encerkan dengan air (1:10) secara perlahan.\nLangkah 3: Reduksi Cr(VI) menjadi Cr(III) dengan natrium tiosulfat atau besi(II) sulfat.\nLangkah 4: Netralisasi dan endapkan kromium hidroksida.\nLangkah 5: Serahkan ke pengelola limbah B3 bersertifikat.",
    },
    "Natrium Azida": {
        "rumus": "NaN3",
        "simbol_bahaya": "Beracun eksplosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Eksplosif jika terkena panas, gesekan, atau benturan; bereaksi dengan asam menghasilkan asam azida (HN3) yang sangat eksplosif dan beracun",
        "pengelolaan_limbah": "PERHATIAN EKSPLOSIF!\nLangkah 1: Jangan terkena panas, gesekan, atau benturan.\nLangkah 2: Simpan dalam wadah asli, jangan dipindahkan jika tidak perlu.\nLangkah 3: Beri label 'LIMBAH EKSPLOSIF - JANGAN DIGETARKAN'.\nLangkah 4: Segera serahkan ke pengelola limbah B3 khusus bahan eksplosif.",
    },
    "Natrium Klorida": {
        "rumus": "NaCl",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak reaktif terhadap air, udara, atau asam encer; terdisosiasi sempurna dalam air menjadi ion Na+ dan Cl-",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.\nLangkah 4: Untuk padatan, buang ke tempat sampah non-organik jika tidak terkontaminasi.",
    },
    "Kalium Klorida": {
        "rumus": "KCl",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak reaktif terhadap air, udara, atau asam encer; terdisosiasi sempurna dalam air menjadi ion K+ dan Cl-",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.\nLangkah 4: Untuk padatan, buang ke tempat sampah non-organik jika tidak terkontaminasi.",
    },
    "Kalsium Klorida": {
        "rumus": "CaCl2",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Higroskopis kuat (menyerap air dari udara); bereaksi eksotermis dengan air; stabil pada suhu kamar; tidak reaktif terhadap logam",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Magnesium Sulfat": {
        "rumus": "MgSO4",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; larut dalam air (eksotermis ringan); tidak reaktif terhadap asam dan basa encer; higroskopis (menyerap air dari udara)",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Natrium Sulfat": {
        "rumus": "Na2SO4",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak reaktif terhadap air, udara, atau asam/basa encer; larut dalam air dengan sedikit perubahan suhu",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Natrium Karbonat": {
        "rumus": "Na2CO3",
        "simbol_bahaya": "Iritasi",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Basa lemah; bereaksi dengan asam menghasilkan gas CO2 (effervescence); bereaksi dengan ion logam membentuk endapan karbonat; hidrolisis menghasilkan OH-",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah berlabel 'LIMBAH BASA LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi dengan asam encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Natrium Bikarbonat": {
        "rumus": "NaHCO3",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil dalam bentuk padat; terurai pada suhu >50C menjadi Na2CO3, H2O, dan CO2; bereaksi dengan asam menghasilkan CO2 (effervescence); buffer pH",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Tembaga(II) Sulfat": {
        "rumus": "CuSO4",
        "simbol_bahaya": "Beracun lingkungan",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; anhidrat (putih) menjadi biru saat hidrasi; bereaksi dengan basa membentuk endapan Cu(OH)2 biru; toksik bagi organisme akuatik",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH LOGAM BERAT'.\nLangkah 2: Jangan campur dengan limbah organik atau asam kuat.\nLangkah 3: Endapkan logam dengan basa jika memungkinkan.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk daur ulang logam atau pengolahan khusus.\nLangkah 5: Limbah ini bersifat bioakumulatif \u2014 jangan dibuang ke lingkungan.",
    },
    "Besi(III) Klorida": {
        "rumus": "FeCl3",
        "simbol_bahaya": "Korosif",
        "wujud": "Padatan",
        "bau": "Tajam",
        "reaktivitas": "Higroskopis kuat; bereaksi dengan air membentuk larutan asam (hidrolisis); mengoksidasi logam tertentu; korosif terhadap banyak logam; larutan kuning-coklat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH B3 - KOROSIF'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi dengan NaOH encer hingga pH 6-8 (terbentuk endapan Fe(OH)3).\nLangkah 4: Saring endapan, keringkan, buang ke limbah B3 padat.\nLangkah 5: Filtrat cair dapat dibuang ke saluran pembuangan.",
    },
    "Amonium Klorida": {
        "rumus": "NH4Cl",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; terurai pada suhu tinggi menjadi NH3 dan HCl; bereaksi dengan basa kuat menghasilkan gas amonia; larut dalam air (endotermis)",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Fenolftalein": {
        "rumus": "C20H14O4",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; tidak reaktif dalam kondisi normal; berubah warna dari tidak berwarna menjadi merah muda pada pH >8,3 (indikator asam-basa)",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Metil Jingga": {
        "rumus": "C14H14N3NaO3S",
        "simbol_bahaya": "Iritasi",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; berubah warna dari merah (pH <3,1) menjadi jingga/kuning (pH >4,4); indikator pH yang umum dalam titrasi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "EDTA": {
        "rumus": "C10H16N2O8",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; membentuk kompleks kelat dengan ion logam divalen dan trivalen (Ca2+, Mg2+, Fe3+); agen pengkhelat kuat; larut dalam basa",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Pereaksi Biuret": {
        "rumus": "Biuret reagent",
        "simbol_bahaya": "Iritasi",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan ikatan peptida dalam suasana basa membentuk kompleks ungu; digunakan untuk uji protein; peka terhadap cahaya",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Pereaksi Ninhidrin": {
        "rumus": "C9H6O4",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan asam amino membentuk kompleks ungu (Reaksi Ninhidrin); sensitif terhadap cahaya; digunakan dalam kromatografi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Perak Nitrat": {
        "rumus": "AgNO3",
        "simbol_bahaya": "Oksidator korosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sensitif terhadap cahaya (fotoreaktif); terurai terkena cahaya menjadi perak metalik (hitam); bereaksi dengan klorida membentuk endapan AgCl putih; oksidator ringan",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik atau kaca berlabel 'LIMBAH B3 - OKSIDATOR'. Jangan campur dengan bahan organik.\nLangkah 2: Encerkan dengan air (1:10) secara perlahan.\nLangkah 3: Reduksi perak dengan Na2S2O3 atau klorida.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk daur ulang logam mulia.",
    },
    "Glukosa": {
        "rumus": "C6H12O6",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Manis",
        "reaktivitas": "Stabil pada suhu kamar; dapat mengalami fermentasi oleh ragi menjadi etanol dan CO2; bereaksi dengan oksidator kuat; mereduksi ion logam (Cu2+, Ag+); gula pereduksi",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.\nLangkah 3: Untuk padatan, buang ke tempat sampah non-organik jika bersih.",
    },
    "Sukrosa": {
        "rumus": "C12H22O11",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Manis",
        "reaktivitas": "Stabil pada suhu kamar; terhidrolisis dalam asam menjadi glukosa dan fruktosa (gula invert); tidak mereduksi ion logam; dapat mengalami karamelisasi pada suhu tinggi",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.\nLangkah 3: Untuk padatan, buang ke tempat sampah non-organik jika bersih.",
    },
    "Sodium Dodesil Sulfat": {
        "rumus": "SDS",
        "simbol_bahaya": "Iritasi",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bersifat surfaktan (menurunkan tegangan permukaan); bereaksi dengan protein (denaturasi); membentuk misel dalam air; iritasi kulit",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan larutan SDS dalam wadah berlabel 'LIMBAH SDS - SURFAKTAN'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Netralisasi pH jika perlu.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Polietilen Glikol": {
        "rumus": "PEG",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Cairan kental",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak reaktif terhadap asam/basa encer; larut dalam air dan pelarut organik; bersifat higroskopis; inert secara biologis",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah berlabel 'LIMBAH MINYAK/GLIKOL'.\nLangkah 2: Jumlah kecil dapat dibuang ke tempat sampah setelah diserap dengan absorben.\nLangkah 3: Jumlah besar serahkan ke pengelola limbah.",
    },
    "Akrilonitril": {
        "rumus": "C3H3N",
        "simbol_bahaya": "Mudah terbakar beracun",
        "wujud": "Cairan",
        "bau": "Tajam",
        "reaktivitas": "Mudah terbakar; bereaksi polimerisasi dengan katalis; bereaksi dengan oksidator kuat; toksik dan karsinogenik; dapat terpolimerisasi eksotermis jika tanpa inhibitor",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - TOKSIK REAKTIF'.\nLangkah 2: Hindari kontak langsung dan inhalasi \u2014 karsinogenik.\nLangkah 3: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus.",
    },
    "Formaldehid": {
        "rumus": "CH2O",
        "simbol_bahaya": "Beracun karsinogen",
        "wujud": "Cairan/gas",
        "bau": "Tajam",
        "reaktivitas": "Bereaksi dengan protein melalui reaksi silang (fiksasi jaringan); teroksidasi menjadi asam format; mudah terpolimerisasi membentuk paraformaldehid; toksik dan iritasi kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - TOKSIK REAKTIF'.\nLangkah 2: Hindari kontak langsung dan inhalasi \u2014 karsinogenik.\nLangkah 3: Oksidasi ringan dengan NaHSO3 jika perlu.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus.",
    },
    "Glutaraldehid": {
        "rumus": "C5H8O2",
        "simbol_bahaya": "Beracun",
        "wujud": "Cairan",
        "bau": "Tajam",
        "reaktivitas": "Bereaksi dengan protein melalui reaksi silang (fiksasi); lebih stabil dari formaldehid; aktif sebagai disinfektan; bereaksi dengan gugus amina; iritasi kulit dan mukosa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - TOKSIK REAKTIF'.\nLangkah 2: Hindari kontak langsung dan inhalasi.\nLangkah 3: Serahkan ke pengelola limbah B3 bersertifikat untuk pengolahan khusus.",
    },
    "Benzoil Peroksida": {
        "rumus": "C14H10O4",
        "simbol_bahaya": "Eksplosif iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Eksplosif jika dipanaskan atau terkena gesekan; terurai menjadi radikal bebas; inisiator polimerisasi; bereaksi hebat dengan bahan pereduksi; oksidator kuat",
        "pengelolaan_limbah": "PERHATIAN EKSPLOSIF!\nLangkah 1: Jangan terkena panas, gesekan, atau benturan.\nLangkah 2: Simpan dalam wadah asli, jangan dipindahkan jika tidak perlu.\nLangkah 3: Beri label 'LIMBAH EKSPLOSIF - JANGAN DIGETARKAN'.\nLangkah 4: Segera serahkan ke pengelola limbah B3 khusus bahan eksplosif.",
    },
    "Asam Benzoat": {
        "rumus": "C7H6O2",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Khas",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa membentuk garam benzoat; dapat mengalami sublimasi pada suhu tinggi; bersifat antimikroba dalam bentuk asam",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Air": {
        "rumus": "H2O",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Cairan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; pelarut universal; bereaksi dengan logam alkali dan alkali tanah (menghasilkan H2); hidrolisis banyak senyawa; tidak beracun",
        "pengelolaan_limbah": "Langkah 1: Buang langsung ke saluran pembuangan.\nLangkah 2: Air limbah tidak mengandung kontaminan berbahaya \u2014 aman dibuang.",
    },
    "Asam Sitrat": {
        "rumus": "C6H8O7",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa membentuk garam sitrat; mengkhelat ion logam (sequestrant); bereaksi dengan logam menghasilkan gas H2; asam trikarboksilat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Format": {
        "rumus": "HCOOH",
        "simbol_bahaya": "Korosif",
        "wujud": "Cairan",
        "bau": "Menyengat",
        "reaktivitas": "Reaktif terhadap logam menghasilkan gas H2 dan format; bereaksi dengan basa membentuk garam format; dapat terdekomposisi pada suhu tinggi menjadi CO dan H2O; reduktor",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Oksalat": {
        "rumus": "H2C2O4",
        "simbol_bahaya": "Beracun",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Bereaksi dengan basa membentuk garam oksalat; mengkhelat ion logam (Ca2+ membentuk endapan CaC2O4); reduktor yang dapat dioksidasi oleh KMnO4; beracun",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Pikrat": {
        "rumus": "C6H3N3O7",
        "simbol_bahaya": "Eksplosif beracun",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Eksplosif jika terkena panas, gesekan, atau benturan; bereaksi dengan basa membentuk garam pikrat yang lebih eksplosif; oksidator kuat; mudah meledak saat kering",
        "pengelolaan_limbah": "PERHATIAN EKSPLOSIF: JANGAN DIKERINGKAN ATAU DIGETARKAN!\nLangkah 1: Jaga tetap basah dengan air (minimal 10% air).\nLangkah 2: Kumpulkan dalam wadah plastik khusus berlabel 'LIMBAH EKSPLOSIF - ASAM PIKRAT'.\nLangkah 3: Hindari gesekan, panas, dan benturan selama penanganan.\nLangkah 4: Serahkan segera ke pengelola limbah B3 khusus bahan eksplosif.",
    },
    "Asam Borat": {
        "rumus": "H3BO3",
        "simbol_bahaya": "Beracun",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan alkohol membentuk ester borat (nyala hijau); asam lemah; bersifat antiseptik ringan; toksik jika tertelan dalam jumlah besar",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Laktat": {
        "rumus": "C3H6O3",
        "simbol_bahaya": "Iritasi",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa membentuk garam laktat; dapat teroksidasi menjadi asam piruvat; higroskopis; produk fermentasi bakteri asam laktat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Tartarat": {
        "rumus": "C4H6O6",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa membentuk garam tartrat; mengkhelat ion logam; membentuk kristal dengan kalium (cream of tartar); asam dikarboksilat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Barium Hidroksida": {
        "rumus": "Ba(OH)2",
        "simbol_bahaya": "Beracun korosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Bereaksi dengan asam membentuk garam barium; menyerap CO2 dari udara membentuk BaCO3; larutan basa kuat; toksik jika tertelan; bereaksi dengan Al dan Zn menghasilkan H2",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH LOGAM BERAT'.\nLangkah 2: Jangan campur dengan limbah organik atau asam kuat.\nLangkah 3: Serahkan ke pengelola limbah B3 untuk daur ulang logam atau pengolahan khusus.\nLangkah 4: Limbah ini bersifat bioakumulatif \u2014 jangan dibuang ke lingkungan.",
    },
    "Litium Hidroksida": {
        "rumus": "LiOH",
        "simbol_bahaya": "Korosif",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Bereaksi dengan asam membentuk garam litium; menyerap CO2 dari udara; higroskopis; bereaksi dengan Al dan Zn menghasilkan H2; basa kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tahan basa (plastik HDPE), beri label 'LIMBAH B3 - BASA KUAT'.\nLangkah 2: Netralisasi perlahan dengan larutan HCl 10% atau H2SO4 encer sambil diaduk hingga pH 6-8.\nLangkah 3: Encerkan dengan air mengalir (1:10).\nLangkah 4: Buang ke saluran pembuangan atau serahkan ke pengelola limbah B3.",
    },
    "Magnesium": {
        "rumus": "Mg",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Reaktif terhadap asam (encer dan pekat) menghasilkan gas H2; mudah terbakar di udara jika dipanaskan (nyala putih terang); bereaksi lambat dengan air panas",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan Mg dalam wadah kering berlabel 'LIMBAH LOGAM REAKTIF - Mg'.\nLangkah 2: Jangan campur dengan air (risiko H2 eksplosif).\nLangkah 3: Simpan di tempat kering, jauh dari api.\nLangkah 4: Serahkan ke pengelola limbah B3 atau daur ulang logam.",
    },
    "Aluminium": {
        "rumus": "Al",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Membentuk lapisan oksida (Al2O3) pelindung; bereaksi dengan asam kuat dan basa kuat (amfoter) menghasilkan H2; stabil pada suhu kamar karena pasivasi",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan/logam dalam wadah kering berlabel 'LIMBAH LOGAM'.\nLangkah 2: Jangan campur dengan asam (risiko H2).\nLangkah 3: Keringkan dan serahkan ke pengelola daur ulang logam.\nLangkah 4: Limbah non-B3 dapat dibuang ke tempat sampah logam terpisah.",
    },
    "Besi": {
        "rumus": "Fe",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Bereaksi lambat dengan asam encer menghasilkan H2; berkarat di udara lembab (oksidasi menjadi Fe2O3); tidak reaktif terhadap basa; dapat mengalami oksidasi lanjut",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan/logam dalam wadah kering berlabel 'LIMBAH LOGAM'.\nLangkah 2: Keringkan dan serahkan ke pengelola daur ulang logam.\nLangkah 3: Limbah non-B3 dapat dibuang ke tempat sampah logam terpisah.",
    },
    "Tembaga": {
        "rumus": "Cu",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Tidak reaktif terhadap air dan asam non-oksidator; bereaksi dengan HNO3 dan H2SO4 panas menghasilkan NOx/SO2; membentuk patina hijau (CuCO3) di udara lembab",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan/logam dalam wadah kering berlabel 'LIMBAH LOGAM'.\nLangkah 2: Keringkan dan serahkan ke pengelola daur ulang logam.\nLangkah 3: Limbah non-B3 dapat dibuang ke tempat sampah logam terpisah.",
    },
    "Timbal": {
        "rumus": "Pb",
        "simbol_bahaya": "Beracun lingkungan",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Tahan korosi membentuk lapisan PbO pelindung; bereaksi lambat dengan asam kuat; bereaksi dengan air sadah membentuk endapan PbCO3; toksik dan bioakumulatif",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH LOGAM BERAT'.\nLangkah 2: Jangan campur dengan limbah organik atau asam kuat.\nLangkah 3: Serahkan ke pengelola limbah B3 untuk daur ulang logam atau pengolahan khusus.\nLangkah 4: Limbah ini bersifat bioakumulatif \u2014 jangan dibuang ke lingkungan.",
    },
    "Karbon Aktif": {
        "rumus": "C",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; mengadsorpsi gas dan molekul organik (fisiosorpsi); tidak reaktif secara kimia; inert terhadap asam/basa; regenerasi dengan pemanasan",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan dalam wadah tertutup.\nLangkah 2: Karbon aktif dapat diregenerasi dengan pemanasan.\nLangkah 3: Jika terkontaminasi zat berbahaya, perlakukan sesuai kontaminannya.\nLangkah 4: Buang ke tempat sampah non-organik jika bersih.",
    },
    "Silika Gel": {
        "rumus": "SiO2",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Higroskopis kuat menyerap uap air hingga 40% berat; stabil pada suhu kamar; inert terhadap asam dan basa; regenerasi dengan pemanasan 150C; desikan",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan dalam wadah tertutup.\nLangkah 2: Jika terkontaminasi zat berbahaya, perlakukan sesuai kontaminannya.\nLangkah 3: Buang ke tempat sampah non-organik jika bersih.",
    },
    "Metana": {
        "rumus": "CH4",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Gas",
        "bau": "Tidak berbau",
        "reaktivitas": "Mudah terbakar membakar dengan nyala biru; bereaksi dengan halogen (klorinasi) dengan UV; membentuk campuran eksplosif dengan udara (5-15%); gas rumah kaca",
        "pengelolaan_limbah": "Langkah 1: Biarkan menguap di area berventilasi tinggi (lemari asam) dalam jumlah kecil.\nLangkah 2: Jangan buang ke saluran tertutup (risiko ledakan).\nLangkah 3: Untuk jumlah besar \u2014 serahkan ke pengelola limbah gas.\nLangkah 4: Pastikan tidak ada api atau percikan di area penanganan.",
    },
    "Propana": {
        "rumus": "C3H8",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Gas",
        "bau": "Tidak berbau",
        "reaktivitas": "Mudah terbakar membakar menghasilkan CO2 dan H2O; bereaksi dengan halogen (substitusi radikal bebas); komponen LPG; gas lebih berat dari udara",
        "pengelolaan_limbah": "Langkah 1: Biarkan menguap di area berventilasi tinggi (lemari asam) dalam jumlah kecil.\nLangkah 2: Jangan buang ke saluran tertutup (risiko ledakan).\nLangkah 3: Untuk jumlah besar \u2014 serahkan ke pengelola limbah gas.\nLangkah 4: Pastikan tidak ada api atau percikan di area penanganan.",
    },
    "Butana": {
        "rumus": "C4H10",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Gas",
        "bau": "Tidak berbau",
        "reaktivitas": "Mudah terbakar; reaktivitas mirip propana; digunakan sebagai bahan bakar LPG; stabil pada suhu kamar; substitusi halogenasi dengan katalis UV",
        "pengelolaan_limbah": "Langkah 1: Biarkan menguap di area berventilasi tinggi (lemari asam) dalam jumlah kecil.\nLangkah 2: Jangan buang ke saluran tertutup (risiko ledakan).\nLangkah 3: Untuk jumlah besar \u2014 serahkan ke pengelola limbah gas.\nLangkah 4: Pastikan tidak ada api atau percikan di area penanganan.",
    },
    "Etena": {
        "rumus": "C2H4",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Gas",
        "bau": "Khas",
        "reaktivitas": "Mudah terbakar; bereaksi adisi elektrofilik (halogenasi, hidrogenasi, hidrasi); monomer utama polietilena; bereaksi dengan KMnO4 mengubah warna ungu menjadi coklat",
        "pengelolaan_limbah": "Langkah 1: Biarkan menguap di area berventilasi tinggi (lemari asam) dalam jumlah kecil.\nLangkah 2: Jangan buang ke saluran tertutup (risiko ledakan).\nLangkah 3: Untuk jumlah besar \u2014 serahkan ke pengelola limbah gas.\nLangkah 4: Pastikan tidak ada api atau percikan di area penanganan.",
    },
    "Asetilena": {
        "rumus": "C2H2",
        "simbol_bahaya": "Sangat mudah terbakar",
        "wujud": "Gas",
        "bau": "Khas",
        "reaktivitas": "Sangat mudah terbakar dengan nyala terang (3000C); dapat meledak pada tekanan >1,5 atm; bereaksi adisi; membentuk asetilida eksplosif dengan logam Cu dan Ag",
        "pengelolaan_limbah": "Langkah 1: Biarkan menguap di area berventilasi tinggi (lemari asam) dalam jumlah kecil.\nLangkah 2: Jangan buang ke saluran tertutup (risiko ledakan).\nLangkah 3: Untuk jumlah besar \u2014 serahkan ke pengelola limbah gas.\nLangkah 4: Pastikan tidak ada api atau percikan di area penanganan.",
    },
    "Fenol": {
        "rumus": "C6H5OH",
        "simbol_bahaya": "Beracun korosif",
        "wujud": "Padatan",
        "bau": "Khas",
        "reaktivitas": "Bereaksi dengan basa membentuk garam fenolat; mengalami substitusi elektrofilik lebih mudah dari benzena; toksik dan korosif; teroksidasi oleh udara menjadi warna gelap",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah kaca berlabel 'LIMBAH B3 - FENOL BERACUN'.\nLangkah 2: Jangan campur dengan oksidator kuat.\nLangkah 3: Oksidasi dengan KMnO4 atau H2O2 untuk mengurangi toksisitas.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat \u2014 tidak boleh dibuang ke saluran umum.",
    },
    "Anilina": {
        "rumus": "C6H5NH2",
        "simbol_bahaya": "Beracun",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Bereaksi dengan asam membentuk garam anilinium; teroksidasi oleh udara menjadi warna gelap; dapat mengalami diazotasi; toksik (methemoglobinemia); basa lemah",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - TOKSIK'.\nLangkah 2: Hindari inhalasi dan kontak kulit \u2014 gunakan APD lengkap.\nLangkah 3: Jangan dicampur dengan limbah lain.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi suhu tinggi.",
    },
    "Piridina": {
        "rumus": "C5H5N",
        "simbol_bahaya": "Mudah terbakar beracun",
        "wujud": "Cairan",
        "bau": "Menyengat",
        "reaktivitas": "Mudah terbakar; bersifat basa lemah; bereaksi dengan asam membentuk garam piridinium; pelarut organik umum; menyerap air; toksik bagi sistem saraf",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - TOKSIK'.\nLangkah 2: Hindari inhalasi dan kontak kulit \u2014 gunakan APD lengkap.\nLangkah 3: Jangan dicampur dengan limbah lain.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi suhu tinggi.",
    },
    "Sikloheksana": {
        "rumus": "C6H12",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Cairan",
        "bau": "Khas",
        "reaktivitas": "Mudah terbakar; stabil pada suhu kamar; bereaksi substitusi radikal bebas dengan halogen; inert terhadap asam dan basa; pelarut non-polar",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Karbon Disulfida": {
        "rumus": "CS2",
        "simbol_bahaya": "Sangat mudah terbakar beracun",
        "wujud": "Cairan",
        "bau": "Busuk",
        "reaktivitas": "Sangat mudah terbakar (autoignisi 90C); bereaksi dengan oksidator kuat; toksik bagi sistem saraf; menyerap UV; uap lebih berat dari udara",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR BERACUN'.\nLangkah 2: Simpan di lemari asam, jauh dari api dan oksidator.\nLangkah 3: Jangan dibuang ke saluran pembuangan atau tempat sampah biasa.\nLangkah 4: Serahkan ke pengelola limbah B3 bersertifikat untuk insinerasi atau daur ulang pelarut.",
    },
    "Urea": {
        "rumus": "CO(NH2)2",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; terhidrolisis lambat dalam air menjadi NH3 dan CO2; terurai pada suhu >130C; bereaksi dengan asam membentuk garam urea; pupuk nitrogen",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Natrium Fosfat": {
        "rumus": "Na3PO4",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Basa lemah; bereaksi dengan asam membentuk garam fosfat; bereaksi dengan ion logam membentuk endapan fosfat; larutan buffer; agen pembersih",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Amonium Sulfat": {
        "rumus": "(NH4)2SO4",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa kuat menghasilkan gas NH3; larut dalam air (endotermis); pupuk nitrogen; terurai pada suhu tinggi",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Seng Sulfat": {
        "rumus": "ZnSO4",
        "simbol_bahaya": "Beracun lingkungan",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; higroskopis; larut dalam air; bereaksi dengan basa membentuk endapan Zn(OH)2 putih yang larut dalam basa berlebih (amfoter)",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH LOGAM BERAT'.\nLangkah 2: Jangan campur dengan limbah organik atau asam kuat.\nLangkah 3: Serahkan ke pengelola limbah B3 untuk daur ulang logam atau pengolahan khusus.\nLangkah 4: Limbah ini bersifat bioakumulatif \u2014 jangan dibuang ke lingkungan.",
    },
    "Besi(II) Sulfat": {
        "rumus": "FeSO4",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil dalam bentuk hidrat; teroksidasi oleh udara menjadi Fe(III) coklat; bereaksi dengan basa membentuk endapan Fe(OH)2 hijau yang cepat teroksidasi; reduktor",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Bromtimol Biru": {
        "rumus": "C27H28Br2O5S",
        "simbol_bahaya": "Iritasi",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; indikator pH (kuning pada pH <6, biru pada pH >7,6); tidak reaktif dalam kondisi normal; sensitif terhadap asam dan basa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Metil Merah": {
        "rumus": "C15H15N3O2",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; indikator pH (merah pada pH <4,4, kuning pada pH >6,2); tidak reaktif dalam kondisi normal; digunakan dalam titrasi asam-basa",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Kristal Violet": {
        "rumus": "C25H30ClN3",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; pewarna ungu; bereaksi dengan asam membentuk warna hijau/kuning; digunakan sebagai indikator dan zat warna; antimikroba",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Alizarin Merah": {
        "rumus": "C14H8O4",
        "simbol_bahaya": "Iritasi",
        "wujud": "Serbuk",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; indikator pH (kuning pada pH <5,5, merah pada pH >6,8); membentuk kompleks berwarna dengan ion logam; pewarna mordant",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Polivinil Alkohol": {
        "rumus": "(C2H4O)n",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; larut dalam air panas; tidak reaktif dalam kondisi normal; dapat mengalami reaksi silang dengan agen pengikat silang; higroskopis",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Kreatinin": {
        "rumus": "C4H7N3O",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; larut dalam air; tidak reaktif dalam kondisi normal; produk metabolisme otot; digunakan sebagai biomarker fungsi ginjal",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Urat": {
        "rumus": "C5H4N4O3",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; sukar larut dalam air; bereaksi dengan basa membentuk garam urat; produk metabolisme purin; dapat membentuk kristal (penyebab gout)",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Amonium Hidroksida": {
        "rumus": "NH4OH",
        "simbol_bahaya": "Korosif iritasi",
        "wujud": "Cairan",
        "bau": "Menyengat",
        "reaktivitas": "Basa lemah; larutan amonia dalam air; bereaksi dengan asam membentuk garam amonium; melepaskan gas NH3 jika dipanaskan atau ditambah basa kuat; iritasi kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah tertutup rapat (uap amonia), beri label 'LIMBAH BASA'.\nLangkah 2: Encerkan dengan air (1:5) di area berventilasi.\nLangkah 3: Netralisasi dengan asam encer (HCl 10%) hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Barium Klorida": {
        "rumus": "BaCl2",
        "simbol_bahaya": "Beracun",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; larut dalam air; bereaksi dengan sulfat membentuk endapan BaSO4 putih (uji sulfat); toksik jika tertelan; inert terhadap logam",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah plastik berlabel 'LIMBAH LOGAM BERAT'.\nLangkah 2: Jangan campur dengan limbah organik atau asam kuat.\nLangkah 3: Serahkan ke pengelola limbah B3 untuk daur ulang logam atau pengolahan khusus.",
    },
    "Stronsium Klorida": {
        "rumus": "SrCl2",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; larut dalam air; tidak reaktif dalam kondisi normal; memberikan nyala merah pada uji api; digunakan dalam piroteknik",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Netralisasi pH jika perlu hingga 6-8.\nLangkah 3: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Kurkumin": {
        "rumus": "C21H20O6",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Serbuk",
        "bau": "Khas",
        "reaktivitas": "Stabil pada suhu kamar; indikator pH alami (kuning pada asam, merah pada basa); antioksidan; peka terhadap cahaya UV; membentuk kompleks dengan ion logam",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah cair dalam wadah kaca berlabel 'LIMBAH B3 - INDIKATOR'.\nLangkah 2: Encerkan dengan air (1:10).\nLangkah 3: Serahkan limbah pekat ke pengelola limbah B3.",
    },
    "Asam Sulfanilat": {
        "rumus": "C6H7NO3S",
        "simbol_bahaya": "Iritasi",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Stabil pada suhu kamar; bereaksi dengan basa membentuk garam sulfanilat; dapat mengalami diazotasi (prekursor zat warna azo); larut dalam air panas",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan limbah dalam wadah plastik atau kaca berlabel 'LIMBAH ASAM LEMAH'.\nLangkah 2: Encerkan dengan air (1:5).\nLangkah 3: Netralisasi ringan dengan NaHCO3 atau NaOH encer hingga pH 6-8.\nLangkah 4: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Naftalena": {
        "rumus": "C10H8",
        "simbol_bahaya": "Mudah terbakar",
        "wujud": "Padatan",
        "bau": "Khas",
        "reaktivitas": "Mudah terbakar; bereaksi substitusi elektrofilik lebih mudah dari benzena; menguap pada suhu kamar (bau kapur barus); bereaksi dengan oksidator kuat",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan dalam wadah tertutup rapat berlabel 'LIMBAH B3 - MUDAH TERBAKAR'.\nLangkah 2: Simpan di area sejuk dan berventilasi \u2014 dapat menyublim.\nLangkah 3: Jangan dibuang ke saluran pembuangan.\nLangkah 4: Serahkan ke pengelola limbah B3 untuk insinerasi.",
    },
    "Mineral Oil": {
        "rumus": "Mineral oil",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Cairan kental",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; tidak reaktif terhadap asam/basa; inert secara kimia; tidak mudah terbakar pada suhu kamar; melarutkan senyawa non-polar",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan dalam wadah berlabel 'LIMBAH MINYAK/GLIKOL'.\nLangkah 2: Jumlah kecil dapat dibuang ke tempat sampah setelah diserap dengan absorben.\nLangkah 3: Jumlah besar serahkan ke pengelola limbah.",
    },
    "Gliserol": {
        "rumus": "C3H8O3",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Cairan kental",
        "bau": "Manis",
        "reaktivitas": "Stabil pada suhu kamar; higroskopis; bereaksi dengan asam membentuk ester (gliserida); teroksidasi menjadi gliseraldehida; larut dalam air; tidak beracun",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Oleat": {
        "rumus": "C18H34O2",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Cairan kental",
        "bau": "Khas",
        "reaktivitas": "Stabil pada suhu kamar; dapat teroksidasi oleh udara (ketengikan); bereaksi dengan basa membentuk sabun; asam lemak tak jenuh; hidrogenasi menjadi asam stearat",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.",
    },
    "Asam Stearat": {
        "rumus": "C18H36O2",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; bereaksi dengan basa membentuk sabun; asam lemak jenuh; padatan pada suhu kamar; tidak reaktif dengan air; murni",
        "pengelolaan_limbah": "Langkah 1: Encerkan dengan air minimal 1:10.\nLangkah 2: Buang ke saluran pembuangan dengan air mengalir.\nLangkah 3: Untuk padatan, buang ke tempat sampah non-organik jika bersih.",
    },
    "Parafin Padat": {
        "rumus": "C25H52",
        "simbol_bahaya": "Tidak berbahaya",
        "wujud": "Padatan",
        "bau": "Tidak berbau",
        "reaktivitas": "Sangat stabil pada suhu kamar; inert terhadap asam, basa, dan oksidator ringan; tidak reaktif secara kimia; dapat terbakar pada suhu tinggi; campuran alkana",
        "pengelolaan_limbah": "Langkah 1: Kumpulkan padatan dalam wadah tertutup.\nLangkah 2: Buang ke tempat sampah non-organik jika bersih.",
    },
}
